### ISSUE TITLE
Scrolling issue on all systems

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#231]
steps to reproduce:

1. scroll up
2. send message

expected: scrolls down to show message
actual: does not. message not visible. 

https://zbay.slack.com/files/UTAQELTJ8/F032MT6LD1S/screen_recording_2022-02-10_12.21.47_pm.webm

Related to #236 and #234

**Comment by holmesworcester** [comment]
@vinkabuki is this a duplicate and is it fixed?

**Comment by vinkabuki** [comment]
yes

**Comment by kingalg** [comment]
Version: 0.4.0-alpha.3

Fixed.

**Comment by holmesworcester** [comment]
This broke again after lazy loading fixes in alpha 5a.

**Comment by holmesworcester** [comment]
@Dinek007 @siepra @vinkabuki I have a thought: if the issue is detecting when we are truly scrolled to the bottom, why don't we relax that requirement to say, within 10px or 5% from the bottom? 

As long as we're very near the bottom of the list of messages I think all the behavior we have (scroll down for new messages, "forget" all but the recent messages) makes sense.

**Comment by vinkabuki** [comment]
Makes sense, we just need to make sure that this is the reason why it doesn't work

**Comment by siepra** [comment]
Related PR https://github.com/ZbayApp/monorepo/pull/455

**Comment by kingalg** [comment]
I'm going to check this on Friday or Monday in the office as I don't have Chromebook at home office.

**Comment by holmesworcester** [comment]
@kingalg have you been able to check this yet? 

I'm still seeing errors intermittently. My app gets into a state where scrolling is broken. One hypothesis is that this happens more often as the app gets slowed down by having lots and lots of messages. It might be worth testing this.

**Comment by kingalg** [comment]
@holmesworcester I checked this several times after my comment and everything looks fine. However, as you still expirience that as we agreed I'm going to use chromebook intensively for howeverr long it's take to slow him down and we will see if I experience the same scrolling issue. Task is going to stay here as it is actually in testing stage.

**Comment by kingalg** [comment]
@holmesworcester "finally" I encounter "your" problem. Except now I have this on all systems. We broke something in v 0.8.1-alpha.1

**Comment by kingalg** [comment]
v 0.8.3-alpha.0

Fixed.
