### ISSUE TITLE
Sent messages sometimes hidden behind text entry field

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#236]
Related to #234 

When user sends messages, they sometimes appear partially behind text entry input bar, depending on message length, I think (possibly just on debian vm)

This happens for the first message in a group, and usually not the second message?

**Comment by kingalg** [comment]
not fixed, moved to blocked for now

**Comment by siepra** [comment]
Related to https://github.com/ZbayApp/monorepo/issues/386, fix will be included in https://github.com/ZbayApp/monorepo/pull/401

**Comment by kingalg** [comment]
Version: 0.4.1-alpha.5 

Fixed.

**Comment by holmesworcester** [comment]
Steps to reproduce this in `Quiet-0.8.1-alpha.1.AppImage`

0. On Chromebook
1. Set up two Quiet instances, Alice and Bob in the same channel. Bob sends some message. 
2. Alice sends a message: "test"
3. Bob scrolls up, and scrolls back down again to the bottom of the channel.
4. Alice sends another message: "test"

Repeat steps 3 & 4 until the following happens:

Expected: Alice's message should be completely visible to Bob. 

Actual: Alice's message is partially hidden underneath the text entry field.

**Comment by holmesworcester** [comment]
Closing because we're creating a new issue for this instead.
