### ISSUE TITLE
Application throws error if it's closed during heavy replication

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/monorepo#463]
![image](https://user-images.githubusercontent.com/6099829/164517641-a09c2f1c-2c85-4826-a3d0-10a8cefcdb24.png)

```
2022-04-21T17:26:52.033Z waggle:db Stopping OrbitDB
2022-04-21T17:26:52.090Z waggle:db Stopping IPFS
TypeError: Cannot read properties of null (reading 'length')
    at Replicator.onReplicationProgress (C:\Users\Emi\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\node_modules\orbit-db-store\src\Store.js:98:25)
    at onProgressCallback (C:\Users\Emi\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\node_modules\orbit-db-store\src\Replicator.js:147:14)
    at addToResults (C:\Users\Emi\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\node_modules\ipfs-log\src\entry-io.js:116:17)
    at C:\Users\Emi\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\node_modules\ipfs-log\src\entry-io.js:151:11
C:\Users\Emi\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\lib\libp2p\connectionsManager.js:224
            throw new Error();
            ^

Error
    at process.<anonymous> (C:\Users\Emi\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\lib\libp2p\connectionsManager.js:224:19)
    at process.emit (node:events:390:28)
    at processEmit [as emit] (C:\Users\Emi\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\waggle\node_modules\signal-exit\index.js:197:34)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

**Comment by siepra** [comment]
I think I know this one. It appears when you close the app in the middle of heavy replication, doesn't it?

**Comment by siepra** [comment]
Nevermind, just saw the title

**Comment by holmesworcester** [comment]
should we assume this is fixed in the latest release and QA it?

**Comment by siepra** [comment]
> should we assume this is fixed in the latest release and QA it?

In the logs above we can see the problem lies in networking layer so I'm afraid the answer is no. I'll try to reproduce it and get to the bottom of the problem

**Comment by siepra** [comment]
So here are the logs from closing window. It seems like the OrbitDB has stopped but waggle still tries to replicate (which causes error on reading undefined oplog instance)

`  waggle:db progress 212/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +36ms
  waggle:io Emitting message +36ms
  waggle:conn QmSQZcGJrxAkw9FESCDNkKBAutzjYBeonBxE5SQdqHTMyM connected to QmQrtikuWvA8ukwPAPLbnD6BkqKCNcng3qBA5Ku84DytLL +1s
  frontend:main:main Saved state, closed window +2s
  waggle:db progress 213/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2s
  waggle:io Emitting message +2s
  waggle:db progress 214/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +4ms
  waggle:io Emitting message +5ms
  waggle:db progress 215/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +7ms
  waggle:io Emitting message +5ms
  waggle:db progress 216/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2ms
  waggle:io Emitting message +2ms
  waggle:db progress 217/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2ms
  waggle:io Emitting message +2ms
  waggle:db progress 218/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2ms
  waggle:io Emitting message +2ms
  waggle:db progress 219/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +3ms
  waggle:io Emitting message +3ms
  waggle:db progress 220/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2ms
  waggle:io Emitting message +2ms
  waggle:db progress 221/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +45ms
  waggle:io Emitting message +45ms
  waggle:db progress 222/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +4ms
  waggle:io Emitting message +6ms
  frontend:main:main Event mainWindow.closed +1s
  frontend:main:main Event: app.window-all-closed +0ms
  waggle:socket Closing data server on port 50801 +22s
  waggle:communities Stopping 0 registrars +15s
  waggle:communities Stopped 0 registrars +0ms
  waggle:communities Closing 1 storages +0ms
  waggle:db Stopping OrbitDB +181ms
  waggle:tor May 02 11:29:17.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
  waggle:tor  +9s
  waggle:db progress 223/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +86ms
  waggle:io Emitting message +265ms
  waggle:db progress 224/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +20ms
  waggle:io Emitting message +21ms
  waggle:db progress 225/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2ms
  waggle:io Emitting message +2ms
  waggle:db progress 226/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +36ms
  waggle:io Emitting message +35ms
  waggle:db progress 227/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2ms
  waggle:io Emitting message +2ms
  waggle:db progress 228/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +1ms
  waggle:io Emitting message +1ms
  waggle:db progress 229/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +2ms
  waggle:io Emitting message +2ms
  waggle:db progress 230/906. Address: /orbitdb/zdpuAwyCfYU8ADhsg8xkhZUPwr2fVFzhGKeFAMVeeUNFXt8mc/channels.spam +56ms
  waggle:io Emitting message +56ms
TypeError: Cannot read properties of null (reading 'length')`

**Comment by siepra** [comment]
It's OrbitDB problem. I opened an issue and prepared a sample repo that illustrates the problem
https://github.com/orbitdb/orbit-db-store/issues/121

**Comment by siepra** [comment]
Patched with version 0.28.5 (orbitdb)

**Comment by siepra** [comment]
This issue is also related as it resolves problems with performance regressions https://github.com/ZbayApp/monorepo/issues/491

**Comment by siepra** [comment]
Related PR https://github.com/ZbayApp/monorepo/pull/490
