### ISSUE TITLE
Quiet doesn't always recover after force quit / ctrl+c

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#469]
Here's how this bug presents to me:

1. I leave my chromebook on sleep for some time with Quiet open 
2. I return and Quiet is still running in Terminal but the window is missing. 
3. I Ctrl-C in terminal to quit it. Seems like it works.
4. I run again and Quiet is broken. Sender information doesn't load and I can't send messages without a crash.
5. Restart required. 

We have errors with lockfiles that happen when Quiet is force quit that prevent Quiet from connecting to Tor. This should not happen. 

What's the best way to track down these problems?

I feel like we might need e2e tests that force quit Quiet in all of the states we can enumerate and confirm that it restarts without errors. But I'm interested in other suggestions.

**Comment by holmesworcester** [comment]
Marek's ideas:

a) we just delete lockfile and hope for the best
b) we clean up everything and re-sync from the network
c) some middle ground - we take snapshots (backups), so that we don't have to start from scratch, when resyncing - we can start from the backup

**Comment by holmesworcester** [comment]
It seems like we should try option a. above, and make a barrage of tests for it to ensure things work correctly. then if they don't we can discuss.

**Comment by holmesworcester** [comment]
A related problem is that the main Quiet window is failing to appear on wake from sleep. App logs look normal but there's no main window, no icon, and no way to create a main window.

**Comment by kingalg** [comment]
It seams to be working now. I tried force quitting quiet and putting computers to sleep (as two separate tests) on all systems and didn't encounter any problems.
