### ISSUE TITLE
Messages briefly appear without sender information

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#479]
steps to reproduce: start Quiet in a community with messages

expected: messages only appear once we can display all sender information. messages never appear without sender information.

actual: messages briefly appear without sender information.

note: we should not merely speed this up or make this less visible; instead we should make it so that it is logically impossible for messages to appear without their sender information. no sender information, no message display. 

and tests should confirm this

**Comment by siepra** [comment]
Related PR https://github.com/ZbayApp/monorepo/pull/480
