### ISSUE TITLE
changing package.json has no effect on package-lock.json

### ISSUE THREAD

**Issue by vinkabuki** [TryQuiet/monorepo#513]
Any changes in package.json are ignored by npm, I could literally delete all dependencies, I've bootstrapped the project and it was ignored

**Comment by holmesworcester** [comment]
Is this working again?

**Comment by EmiM** [comment]
Some time ago we added ignoring mobile package in `lerna bootstrap`. This caused the confusion because lerna needs (?) ALL packages to be bootstrapped in order to update package-locks. 
So the "solution" is to bootstrap all packages including mobile.
