### ISSUE TITLE
Scroll position handling on images load

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#523]
Requirements:

- When a new message comes in with an image, user should be able to see the whole image.
- If you are scrolled to the bottom of the chat, and an image loads from an earlier message that you cannot see, you should still be scrolled to the bottom.

Anything else?

**Comment by holmesworcester** [comment]
What is this blocked by?

**Comment by siepra** [comment]
I guess it got solved by adding images placeholders (with the height of an image)
