### ISSUE TITLE
User should see nice placeholder when an image has not yet downloaded

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#526]
Designs here: https://www.figma.com/file/68ucD6gpOAXW1kRNq2gjFK/Send-and-receive-files?node-id=136%3A19360

**Comment by EmiM** [comment]
https://github.com/TryQuiet/monorepo/pull/581

**Comment by EmiM** [comment]
Also added displaying file name above the uploaded picture

**Comment by kingalg** [comment]
v 0.8.3-alpha.0

Currently placeholder looks like this.

<img width="384" alt="Screenshot 2022-06-22 at 13 23 06" src="https://user-images.githubusercontent.com/68909168/175017454-b65badd7-9f03-4bc7-ab6f-5c5d1852999c.png">
