### ISSUE TITLE
User should be able to see when someone new joins a community

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#54]
In Zbay we had a notification that a user had been added to a community. In Quiet we should add this back.

Two options (I think #2 is the right choice because it's so simple, but it's not the best)

1. We could do it the way we did it before, where there was a special kind of message that displayed in the channel (should be #general i think) when we see that a new user has been added. This would appear as coming from a "bot" called "Quiet" with the Quiet logo, and we could use it for other meta level messages.

2. We could have the owner/registrar send the message "@username joined community-name" to the #general channel after they complete the process of adding that user. We do something like this already for new channel creation. 

The second is less good because the owner can spoof that message just by typing it, even when they did not add a user. But it's also really simple. And it reinforces that the owner is the one responsible for adding people.

**Comment by holmesworcester** [comment]
is this done?

**Comment by kingalg** [comment]
I see that option 2 has been chosen and implemented. If yes - It's done and is working correctly.
