### ISSUE TITLE
Native files dialog is hidden under the main window (linux)

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/monorepo#562]
Ubuntu 21.10
Quiet-0.7.0-alpha.0

Opening uploading files dialog ('+' icon in messages input) second time shows dialog under the application window:

![image](https://user-images.githubusercontent.com/6099829/171853837-c32d3359-b544-485b-b032-00e9c94207ec.png)

I found an issue describing exact same problem:
https://github.com/electron/electron/issues/20025
What's more interesting some people encounter this error in vscode: https://github.com/microsoft/vscode/issues/150159

**Comment by EmiM** [comment]
Another thread found: https://github.com/electron/electron/issues/32857

**Comment by EmiM** [comment]
We can try the workaround with using `<input type="file">` but I am not sure If this is going to work out.
https://github.com/TryQuiet/monorepo/pull/603

**Comment by kingalg** [comment]
v 0.9.7-alpha.3 

Fixed.

**Comment by majikat768** [comment]
I'm still having this problem, on ubuntu 22.04.
