### ISSUE TITLE
Missing logo on update screen, on Mac

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#566]
![image](https://user-images.githubusercontent.com/213678/171883356-fa95feea-0d67-433d-99bf-7c0c1bbfc4cb.png)

Lisa (llaro in Quiet) encountered this issue updating to the most recent version.

**Comment by holmesworcester** [comment]
I think this might be fixed in the latest version. @kingalg can you confirm?

**Comment by kingalg** [comment]
It's fixed. I think that this task is duplicated because I'm quite sure that I've closed task like this long time ago.
