### ISSUE TITLE
User can still interact with app after clicking "update now" (confusing!)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#567]
Quiet user llaro reports that she was able to keep interacting with the app (switching channels, etc) after clicking "Update Now". 

I see this as well, though for a shorter period of time than she did.

This is confusing because she thought that clicking on a channel made the app crash. 

Once you click "update" we should show a "Restarting Quiet..." spinner for enough time for the user to see and understand what's happening. 

Another issue is that reopening the app either a) failed or b) took some time so she opened the app again from the icon on her desktop. This opened the *old* app because the update had not finished yet. This cycle continued like 3 times until she got the actual update. 

My hypothesis is that she would have known to wait to restart if the app had told her it was restarting and didn't seem like it had crashed. 

But we should confirm that the app restarts on macOS. It would be awesome to have a test for this but it seems likely that this will be really difficult or impossible.

**Comment by holmesworcester** [comment]
I think this might be fixed in the latest version. @kingalg can you confirm?

**Comment by kingalg** [comment]
I confirm, in 0.8.1-alpha.1 I didn't encounter this problem.
