### ISSUE TITLE
White screen on Quiet

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/monorepo#583]
It happened on Mac with M1 (I'm not sure if it's system related as the same day I've managed to install the same version of Quiet without problems twice on the same computer.

During installation process I got white screen that remain in the app even after restart. 

Below you can find logs from terminal and from Console.

Logs from terminal:

➜ DEBUG=waggle* /Applications/Quiet.app/Contents/MacOS/Quiet
Read extra envs: { TEST_MODE: 'true' }
objc[39254]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb50637948) and /Applications/Quiet.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1127de9c8). One of the two will be used. Which one is undefined.
Error returned: <dictionary: 0x7ff84f292740> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7ff84f2928d8> { length = 18, contents = "Connection invalid" }
}
(node:39259) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/@quiet/backend/node_modules/@quiet/state-manager/node_modules/factory-girl/package.json' of './src/index'. Please either fix that or report it to the module author
(Use `Quiet Helper --trace-deprecation ...` to show where the warning was created)
grep: Support/Quiet/TorDataDirectory: No such file or directory
WebContents #1 called ipcRenderer.sendSync() with 'electron-store-get-data' channel without listeners.
WebContents #2 called ipcRenderer.sendSync() with 'electron-store-get-data' channel without listeners.
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).

Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update
Checking for update (already in progress)
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
(node:39253) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [MacUpdater]. Use emitter.setMaxListeners() to increase limit
(Use `Quiet --trace-warnings ...` to show where the warning was created)
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
(node:39253) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 checking-for-update listeners added to [MacUpdater]. Use emitter.setMaxListeners() to increase limit
(node:39253) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update-not-available listeners added to [MacUpdater]. Use emitter.setMaxListeners() to increase limit
(node:39253) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update-available listeners added to [MacUpdater]. Use emitter.setMaxListeners() to increase limit
(node:39253) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update-downloaded listeners added to [MacUpdater]. Use emitter.setMaxListeners() to increase limit
Checking for update
Update for version 0.7.1-alpha.2 is not available (latest version: 0.7.1-alpha.2, downgrade is disallowed).
Checking for update

Console: 

<img width="555" alt="Screenshot 2022-06-07 at 10 39 52" src="https://user-images.githubusercontent.com/68909168/172336335-b74e021f-3d4d-4e3e-a26d-1ed81a328167.png">

**Comment by vinkabuki** [comment]
Ignore terminal logs, the problem is obviously in console. I've got backup so whoever works on this I can share with you.

**Comment by EmiM** [comment]
https://github.com/TryQuiet/monorepo/pull/600
