### ISSUE TITLE
"Quiet" is damaged and can't be open - popup

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/monorepo#586]
While trying to install Quiet on Mac I got popup from the system suggesting that Quiet is damaged. What is strange is that I already used that install several times the same day on this computer and nothing like this happened.

What I did - removed everything form the previous version (which means removing Quiet from Applications and from Applications Support). I've clicked on downloaded version and moved "Quiet" to Applications in an usual Mac popup. Then I got information as below and I couldn't do anything beside moving app to the bin.

<img width="978" alt="Screenshot 2022-06-07 at 12 57 26" src="https://user-images.githubusercontent.com/68909168/172363405-3edd47d2-08ea-41d8-9dea-f9066caa6b72.png">

**Comment by EmiM** [comment]
I'm wondering if we can do something about it. It looks like macos just decided to put Quiet into quarantine.
I think you can check it by typing this command in terminal:
`xattr -l <path/to/quietApp>`
if it returned `com.apple.quarantine` then you can try to remove the flag with
`xattr -r -d com.apple.quarantine <path/to/quietApp>`
and then run the app.

You can also uninstall this Quiet, download and install it again and check if the error is still happening.

**Comment by kingalg** [comment]
@holmesworcester  I've got two MacOS - BigSur and Montery (as they are most popular right now). Both are up to date. This particular bug happened on MacOS Monterey 12.4. 

It happened to me only once and reinstalling didn't work - what actually worked was restarting computer. So far I wasn't able to replicate it.

**Comment by kingalg** [comment]
Couldn't replicate it. It can be some one time strange MacOs behaviour. Emilia thinks that Mac could have put Quiet on temporary quarantine. As it fixed itself with restart and didn't caused any other issues later on the same app I'm closing this task.
