### ISSUE TITLE
Message height differs between placeholder and actual image (~1-2px difference)

### ISSUE THREAD

**Issue by siepra** [TryQuiet/monorepo#606]
It causes problems with scroll.
The best way to see the problem is to switch between 'ImagePlaceholder' and 'SentImage' scenarios on storybook

**Comment by holmesworcester** [comment]
Note: we can fix this directly or fix it by adding a new messages indicator, up to whoever gets this which is easier.

**Comment by holmesworcester** [comment]
Here's the design we have: https://www.figma.com/file/QZ9pEcCV2AKc6JHPJhgFqV/New-messages-and-date-bars?node-id=11%3A348

Another simpler approach is to show a floating icon in the bottom right with an arrow pointing down. Clicking on this jumps you to the bottom of the scroll and then the button disappears. We don't have a design for this.

**Comment by siepra** [comment]
Changes included in this PR https://github.com/TryQuiet/monorepo/pull/612
