### ISSUE TITLE
User is not able to drag images to Quiet on Chromebook

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/monorepo#619]
v. 0.8.1-alpha.1
System: Chromebook

**How it's working** - User is not able to drag images to Quiet on Chromebook. Or drag anything (it shouldn't be possible to add any file that is not an image yet but it still should be possible to try and the user should get a pop-up informing that he can only add image). On other systems it's working as expected.

**How it should work** - User should be able to drag images on all platforms including Chromebook.

**Comment by holmesworcester** [comment]
This is known and a limitation of the OS I think. I think it's fine to not fix this.

**Comment by holmesworcester** [comment]
I think this is a platform limitation of using Chromebook in linux. Other apps have the same issue. Closing.
