### ISSUE TITLE
Scrolling issues on all platforms

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/monorepo#620]
v. 0.8.1-alpha.1
Systems - all (except Mac with intel) 

I've encounter several scrolling issues. Below you can find steps to recreate one of them that is most reliable in showing up. I didn't get any of them on Mac with intel (it was updated to 0.8.1-alpha.1 not freshly installed) but in all other systems I've got similar problems. Strange thing is that this bug happens 90% of the time but there are moments when following steps to recreate it I don't get exactly the same results. 

1. scroll up
2. send message
expected: scrolls down to show message
actual on Chromebook: message not visible
actual on Mac and Windows: message visible but if you send second message immediately the same way - second message not visible

I've encounter several other issues when scrolling down doesn't happen on both sides - sender and recipient but they are not so reliable replicateble as the one described above.

Previously encounter bugs with scrolling that seams most closely related to current issue:
#231 Scrolling issue on all systems
#382 New incoming messages hidden on chromebook due to failure to scroll down
#349 Some messages are hidden by scroll after sending
#822 Scrolling issue on public channels
#272 On restart, user should be scrolled to the latest messages in the channel (they aren't)
#366 Scroll position in one channel is affected by scrolling in another channel 
#514 Resizing window loses scroll position

**Comment by holmesworcester** [comment]
PR: https://github.com/TryQuiet/monorepo/pull/632

**Comment by holmesworcester** [comment]
@EmiM do you think this should have a test, just to catch any simple mistake in the future?

**Comment by kingalg** [comment]
v. 0.8.3-alpha.0

No scrolling issues spotted in newest version. All platforms checked.
