### ISSUE TITLE
"Unsupported file" modal gives incorrect information about 10MB image size limit

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#636]
Steps to reproduce:

Try to upload a file that's not an image.

You'll see the incorrect modal.

Solution: remove information about file size limit from modal.

**Comment by kingalg** [comment]
Fixed in 0.8.3-alpha.0

<img width="409" alt="Screenshot 2022-06-21 at 16 55 57" src="https://user-images.githubusercontent.com/68909168/174831125-1c0c57e4-9d6f-474b-b260-a99d9c745197.png">
