### ISSUE TITLE
Make spambot run in start/stop mode

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#641]
It should be possible to start the spambot, stop it, and start it again. 

Which of these is right? Do we need both?

1. Make it so we can run spambot until "something bad happens" (tm) and then stop it.
2. Make it so we can run the spambot, check the app to see if something bad is happening, and then start it again if not, and repeat.

We should do the minimum required to complete #384

**Comment by siepra** [comment]
There's no need to make the bot able to restart. All we need is to keep it running until we kill it with SIGINT
