### ISSUE TITLE
Write script which dumps computer usage data to a file (spambot feature?)

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#642]
We need to search for the point where Quiet breaks by overloading it with messages (total) or message volume (messages/second) or users. 

The goal here is to let us automate the search for the point when it breaks. 

To do that, it may be helpful to have a script that logs system usage data. 

Only do what is necessary to complete #384

**Comment by Dinek007** [comment]
https://github.com/TryQuiet/monorepo/pull/678

**Comment by holmesworcester** [comment]
This is complete I think!
