### ISSUE TITLE
User can see downloaded file in his local file system

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#662]
We need to be able to show users the file in their filesystem, with its actual name, ideally in the Downloads folder or the default OS download folder. If that's not available or easy to detect it can be in a  folder called Quiet-downloads. 

One option is to save/copy this file from IPFS to the local filesystem with the appropriate name, in the appropriate folder.

Another option is to have IPFS store all files "natively" with their actual names and then simply point to them.

**Comment by siepra** [comment]
https://user-images.githubusercontent.com/15381135/177347781-f586b262-5801-4708-aa0a-0ba6be1d8412.mov

**Comment by kingalg** [comment]
v 0.9.5 - it's working.
