### ISSUE TITLE
User should be able to run app directly on Mac without warning.

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#671]

**Comment by siepra** [comment]
Looks like Apple developer ID is not assigned to our builds (see https://support.apple.com/en-us/HT202491)
@holmesworcester can you check if Apple account we use for signing is still valid?

**Comment by holmesworcester** [comment]
There was some new user agreement I needed to accept on login, but other than that I don't see any issues. 

It's possible that it will just work now.

**Comment by siepra** [comment]
We're waiting for the next build to verify if problem disappeared

**Comment by siepra** [comment]
Works

**Comment by kingalg** [comment]
v 0.9.7-alpha.7

Fixed.
