### ISSUE TITLE
Add information about file size to medias metadata

### ISSUE THREAD

**Issue by siepra** [TryQuiet/monorepo#675]

**Comment by siepra** [comment]
File size displays under the file name (1 KB in this example)

**Comment by kingalg** [comment]
v 0.9.5

I confirm that it's implemented as described. 

<img width="505" alt="Screenshot 2022-07-08 at 10 14 42" src="https://user-images.githubusercontent.com/68909168/177948441-d1404c77-4582-44cc-ad85-29f25108915f.png">
